import type { UsageStats } from '../types/index.js';
import rawPricing from './model-pricing.json' with { type: 'json' };

/**
 * Per-token pricing for Anthropic API models (USD per token).
 * The direct API doesn't return total_cost_usd like the Claude Code SDK,
 * so we calculate it from token counts.
 */
interface ModelPricing {
  inputPerToken: number;
  outputPerToken: number;
  cacheReadPerToken: number;
  cacheCreationPerToken: number;
}

/**
 * Pricing built from model-pricing.json (generated by scripts/update-pricing.ts).
 * JSON values are USD per million tokens; we convert to per-token here.
 */
const MODEL_PRICING: Record<string, ModelPricing> = Object.fromEntries(
  Object.entries(rawPricing).map(([id, p]) => [
    id,
    {
      inputPerToken: p.inputPerMTok / 1_000_000,
      outputPerToken: p.outputPerMTok / 1_000_000,
      cacheReadPerToken: p.cacheReadPerMTok / 1_000_000,
      cacheCreationPerToken: p.cacheWritePerMTok / 1_000_000,
    },
  ]),
);

/**
 * Usage shape returned by the Anthropic Messages API.
 */
interface ApiUsage {
  input_tokens: number;
  output_tokens: number;
  cache_read_input_tokens?: number | null;
  cache_creation_input_tokens?: number | null;
}

/**
 * Convert Anthropic API usage to our UsageStats format.
 * Calculates cost from token counts using model pricing.
 *
 * The Anthropic API reports `input_tokens` as only the non-cached portion.
 * We normalize so that `inputTokens` is the *total* input tokens
 * (non-cached + cache_read + cache_creation), with the cache fields
 * being subsets of that total.
 */
export function apiUsageToStats(model: string, usage: ApiUsage): UsageStats {
  const pricing = MODEL_PRICING[model];

  const outputTokens = usage.output_tokens;
  const cacheReadInputTokens = usage.cache_read_input_tokens ?? 0;
  const cacheCreationInputTokens = usage.cache_creation_input_tokens ?? 0;

  // inputTokens is the total: raw API input_tokens + cache subsets.
  const inputTokens = usage.input_tokens + cacheReadInputTokens + cacheCreationInputTokens;

  // Cost: deduct cache subsets from total to get the non-cached portion,
  // then charge each category at its respective rate.
  let costUSD = 0;
  if (pricing) {
    const freshInputTokens = inputTokens - cacheReadInputTokens - cacheCreationInputTokens;
    costUSD =
      freshInputTokens * pricing.inputPerToken +
      outputTokens * pricing.outputPerToken +
      cacheReadInputTokens * pricing.cacheReadPerToken +
      cacheCreationInputTokens * pricing.cacheCreationPerToken;
  }

  return {
    inputTokens,
    outputTokens,
    cacheReadInputTokens,
    cacheCreationInputTokens,
    costUSD,
  };
}
